kotlin.code.style=official

spotlessVersion=6.18.0

kotlinVersion=2.3.0

SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true

signing.password=
signing.keyId=
# use absolute path to the secret key ring file
signing.secretKeyRingFile=

mavenCentralPublishing=true
mavenCentralUsername=
mavenCentralPassword=
